/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author User
 */
public class Analytics extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Analytics.class.getName());

    /**
     * Creates new form Analytics
     */
    public Analytics() {
        initComponents();
        setSize(700, 520);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        viewanylitics = new javax.swing.JButton();
        btnadd1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 399, 102, 41));

        viewanylitics.setBackground(new java.awt.Color(204, 204, 204));
        viewanylitics.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        viewanylitics.setForeground(new java.awt.Color(0, 102, 255));
        viewanylitics.setText("View Analytics");
        viewanylitics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewanyliticsActionPerformed(evt);
            }
        });
        getContentPane().add(viewanylitics, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 229, 323, 120));

        btnadd1.setBackground(new java.awt.Color(204, 204, 204));
        btnadd1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnadd1.setForeground(new java.awt.Color(0, 102, 255));
        btnadd1.setText("Add Student Acadamic Data");
        btnadd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadd1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnadd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 76, 323, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/geometric-1732847_1280.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnadd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadd1ActionPerformed
        acadamicdata ad = new acadamicdata();
        ad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnadd1ActionPerformed

    private void viewanyliticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewanyliticsActionPerformed
        Analyticsview av = new Analyticsview();
        av.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewanyliticsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Analytics().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton viewanylitics;
    // End of variables declaration//GEN-END:variables
}
