/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;








/**
 *
 * @author User
 */
public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        setSize(700,520);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnexit = new javax.swing.JButton();
        btnstdmanagent1 = new javax.swing.JButton();
        btnanalytics1 = new javax.swing.JButton();
        btnreports1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1114, 24, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Academic Progress Analyzer System");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 320, 34));

        btnexit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnexit.setForeground(new java.awt.Color(255, 51, 51));
        btnexit.setText("Exit");
        btnexit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        getContentPane().add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 185, 48));

        btnstdmanagent1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnstdmanagent1.setForeground(new java.awt.Color(51, 102, 255));
        btnstdmanagent1.setText("Student Management");
        btnstdmanagent1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnstdmanagent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstdmanagent1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnstdmanagent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 185, 48));

        btnanalytics1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnanalytics1.setForeground(new java.awt.Color(51, 102, 255));
        btnanalytics1.setText("Analytics");
        btnanalytics1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnanalytics1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnanalytics1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnanalytics1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 185, 48));

        btnreports1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnreports1.setForeground(new java.awt.Color(51, 102, 255));
        btnreports1.setText("Reports");
        btnreports1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnreports1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreports1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnreports1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 185, 48));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img2.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnstdmanagent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstdmanagent1ActionPerformed
        StudentManagement studentmanagemnt = new StudentManagement();
        studentmanagemnt.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnstdmanagent1ActionPerformed

    private void btnanalytics1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnanalytics1ActionPerformed
        Analytics analytics = new Analytics();
        analytics.setVisible(true);
        this.dispose();
        

    }//GEN-LAST:event_btnanalytics1ActionPerformed

    private void btnreports1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreports1ActionPerformed
        Reports reports = new Reports();
        reports.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnreports1ActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    /**
     * @param args the command line arguments
     */
  public static void main(String args[]) {
    /* Set the Windows look and feel */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Windows".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new login().setVisible(true));


}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnanalytics1;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnreports1;
    private javax.swing.JButton btnstdmanagent1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
