/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author User
 */
public class StudentManagement extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentManagement.class.getName());

    /**
     * Creates new form StudentManagement
     */
    public StudentManagement() {
        initComponents();
        setSize(700, 520);
        cmbCourse.addActionListener(e -> generateStudentId());

    txtName.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
    public void insertUpdate(javax.swing.event.DocumentEvent e) { generateStudentId(); }
    public void removeUpdate(javax.swing.event.DocumentEvent e) { generateStudentId(); }
    public void changedUpdate(javax.swing.event.DocumentEvent e) { generateStudentId(); }
    

});

    }
    public class DatabaseManager {
    private static final String URL = "jdbc:mysql://localhost:3306/apas"; // change your_db_name
    private static final String USER = "ch";
    private static final String PASSWORD = "chela";

    public static Connection getConnection() throws SQLException {
        return DriverManager.getConnection(URL, USER, PASSWORD);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        cmbCourse = new javax.swing.JComboBox<>();
        txtStudentId = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        txtUpdateId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnviewdata = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setForeground(new java.awt.Color(0, 51, 204));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, 101, 41));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Student Management");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 240, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Student ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 70, 30));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 230, 30));

        cmbCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SE", "Computer Science", "Business management", "Agri" }));
        getContentPane().add(cmbCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 142, 230, 40));
        getContentPane().add(txtStudentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 230, 30));

        btnadd.setForeground(new java.awt.Color(51, 102, 255));
        btnadd.setText("Add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        getContentPane().add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 110, 40));

        btnclear.setForeground(new java.awt.Color(255, 0, 51));
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 100, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Course");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 60, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Student Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 100, 30));

        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 100, 40));

        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 90, 40));

        txtUpdateId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtUpdateId, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 42, 90, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Update id");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 70, 30));

        btnviewdata.setText("View Data");
        btnviewdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewdataActionPerformed(evt);
            }
        });
        getContentPane().add(btnviewdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 423, 90, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/geometric-1732847_1280.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private final Map<String, String> courseCodes = new HashMap<>() {{
    put("SE", "SE");
    put("Computer Science", "CS");
    put("Business management", "BM");
    put("Agri", "AG");
}};

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);
        this.dispose();
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
                                            
    String name = txtName.getText().trim();
    String course = (String) cmbCourse.getSelectedItem();
    String studentId = txtStudentId.getText();

    if (name.isEmpty() || course == null || studentId.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter a name and select a course.");
        return;
    }

    try (Connection conn = DatabaseManager.getConnection()) {
        String sql = "INSERT INTO student (student_id, name, course) VALUES (?, ?, ?)";
        try (java.sql.PreparedStatement pst = conn.prepareStatement(sql)) {
            pst.setString(1, studentId);
            pst.setString(2, name);
            pst.setString(3, course);
            pst.executeUpdate();
        }

        javax.swing.JOptionPane.showMessageDialog(this, "Student added:\n" + studentId + " - " + name + " (" + course + ")");
    } catch (SQLException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error saving student: " + ex.getMessage());
    }

    // Clear form and increment counter
    txtName.setText("");
    cmbCourse.setSelectedIndex(-1);
    txtStudentId.setText("");
    studentCounter++;


    }//GEN-LAST:event_btnaddActionPerformed
    
            
    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        txtName.setText("");
        cmbCourse.setSelectedIndex(-1);
        txtStudentId.setText("");
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
           String updateId = txtUpdateId.getText().trim();
    String newName = txtName.getText().trim();
    String newCourse = (String) cmbCourse.getSelectedItem();

    if (updateId.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter the Student ID to update.");
        return;
    }

    StringBuilder sql = new StringBuilder("UPDATE student SET ");
    boolean updateName = !newName.isEmpty();
    boolean updateCourse = cmbCourse.getSelectedIndex() != -1;

    if (!updateName && !updateCourse) {
        javax.swing.JOptionPane.showMessageDialog(this, "Enter a new Name or select a Course to update.");
        return;
    }

    if (updateName) sql.append("name = ?");
    if (updateCourse) {
        if (updateName) sql.append(", ");
        sql.append("course = ?");
    }
    sql.append(" WHERE student_id = ?");

    try (Connection conn = DatabaseManager.getConnection();
         java.sql.PreparedStatement pst = conn.prepareStatement(sql.toString())) {

        int index = 1;
        if (updateName) pst.setString(index++, newName);
        if (updateCourse) pst.setString(index++, newCourse);
        pst.setString(index, updateId);

        int rows = pst.executeUpdate();
        if (rows > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Student updated.");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No student found with that ID.");
        }

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Update failed: " + e.getMessage());
    }

    txtName.setText("");
    cmbCourse.setSelectedIndex(-1);
    txtUpdateId.setText("");
    }//GEN-LAST:event_btnupdateActionPerformed

    private void txtUpdateIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateIdActionPerformed
        
    }//GEN-LAST:event_txtUpdateIdActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
                                          
    String id = txtUpdateId.getText().trim();

    if (id.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter a Student ID to delete.");
        return;
    }

    int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to delete ID: " + id + "?", "Confirm Delete", javax.swing.JOptionPane.YES_NO_OPTION);
    if (confirm != javax.swing.JOptionPane.YES_OPTION) return;

    try (Connection conn = DatabaseManager.getConnection()) {
        String sql = "DELETE FROM student WHERE student_id = ?";
        try (java.sql.PreparedStatement pst = conn.prepareStatement(sql)) {
            pst.setString(1, id);
            int affected = pst.executeUpdate();
            if (affected > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Student with ID " + id + " deleted.");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "No student found with ID: " + id);
            }
        }
    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error deleting student: " + ex.getMessage());
    }


    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnviewdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewdataActionPerformed
        viewdata vd = new viewdata();
        vd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnviewdataActionPerformed
    private int getNextIdForCourse(String courseCodePrefix) {
    int max = 0;
    String query = "SELECT student_id FROM student WHERE student_id LIKE ?";

    try (Connection conn = DatabaseManager.getConnection();
         java.sql.PreparedStatement pst = conn.prepareStatement(query)) {

        pst.setString(1, courseCodePrefix + "-%");
        try (java.sql.ResultSet rs = pst.executeQuery()) {
            while (rs.next()) {
                String sid = rs.getString("student_id");
                // Extract number part
                String[] parts = sid.split("-");
                if (parts.length == 2) {
                    try {
                        int num = Integer.parseInt(parts[1]);
                        if (num > max) max = num;
                    } catch (NumberFormatException ignored) {}
                }
            }
        }

    } catch (Exception e) {
    }

    return max + 1;
}

    private void generateStudentId() {
    String name = txtName.getText().trim();
    String course = (String) cmbCourse.getSelectedItem();

    if (!name.isEmpty() && courseCodes.containsKey(course)) {
        String code = courseCodes.get(course);
        int nextNumber = getNextIdForCourse(code);
        String studentId = String.format("%s-%03d", code, nextNumber);
        txtStudentId.setText(studentId);
    } else {
        txtStudentId.setText("");
    }
    txtStudentId.setEditable(false);
  
}
    private static int studentCounter = 1;
    




    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StudentManagement().setVisible(true));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton btnviewdata;
    private javax.swing.JComboBox<String> cmbCourse;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtStudentId;
    private javax.swing.JTextField txtUpdateId;
    // End of variables declaration//GEN-END:variables
}
